version: "2.3"

services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=uzumeshi

  web:
    volumes:
      - uzumeshi-sync:/app:nocopy
    stdin_open: true
    tty: true

volumes:
  uzumeshi-sync:
    external: true

